[package]
name = "pidfile-rs"
version = "0.1.2"
authors = ["Andrej Shadura <andrew.shadura@collabora.co.uk>"]
edition = "2018"
description = "Rust wrapper for pidfile_* functions from libbsd/libutil"
license = "MIT"
repository = "https://github.com/andrewshadura/bsd-pidfile-rs"

[dependencies]
libc = "0.2"
thiserror = "1.0"
log = "0.4"

[target.'cfg(not(any(target_os = "dragonfly", target_os = "freebsd")))'.build-dependencies]
system-deps = "5"

[package.metadata.system-deps.'cfg(not(any(target_os = "dragonfly", target_os = "freebsd")))']
libbsd = "0.1.6"

[dev-dependencies]
tempfile = "3"
nix = "^0.19"
